version: '3.8'

services:
  # PostgreSQL database for integration tests
  test-db:
    image: postgres:17-alpine
    container_name: zitadel-test-db
    environment:
      POSTGRES_DB: zitadel_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zitadel_test"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - test-db-data:/var/lib/postgresql/data
    networks:
      - test-network

  # Optional: PgAdmin for database inspection during development
  test-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: zitadel-test-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - test-db
    networks:
      - test-network
    profiles:
      - tools

volumes:
  test-db-data:
    driver: local

networks:
  test-network:
    driver: bridge
