-- Migration: 001_12 - No-op (position uniqueness not enforced in Go v2)
-- Position is timestamp-based (DECIMAL) and may have duplicates within same transaction
-- in_tx_order handles ordering within same position
