/**
 * SCIM User and Group Schema Definitions
 * RFC 7643 Section 8 - Schema Definitions
 */

import { SCIM_SCHEMAS, SCIMSchema } from '../types';

/**
 * SCIM User Schema (RFC 7643 Section 4.1)
 */
export function getUserSchema(): SCIMSchema {
  return {
    id: SCIM_SCHEMAS.CORE_USER,
    name: 'User',
    description: 'User Account',
    attributes: [
      {
        name: 'userName',
        type: 'string',
        multiValued: false,
        description: 'Unique identifier for the User',
        required: true,
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'server',
      },
      {
        name: 'name',
        type: 'complex',
        multiValued: false,
        description: "The components of the user's real name",
        required: false,
        subAttributes: [
          {
            name: 'formatted',
            type: 'string',
            multiValued: false,
            description: 'The full name',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'familyName',
            type: 'string',
            multiValued: false,
            description: 'The family name',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'givenName',
            type: 'string',
            multiValued: false,
            description: 'The given name',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'middleName',
            type: 'string',
            multiValued: false,
            description: 'The middle name',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'honorificPrefix',
            type: 'string',
            multiValued: false,
            description: 'The honorific prefix',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'honorificSuffix',
            type: 'string',
            multiValued: false,
            description: 'The honorific suffix',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
        ],
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'displayName',
        type: 'string',
        multiValued: false,
        description: 'The name of the User, suitable for display',
        required: false,
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'nickName',
        type: 'string',
        multiValued: false,
        description: 'The casual way to address the user',
        required: false,
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'profileUrl',
        type: 'reference',
        multiValued: false,
        description: 'A URI that points to a resource location',
        required: false,
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'title',
        type: 'string',
        multiValued: false,
        description: "The user's title",
        required: false,
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'userType',
        type: 'string',
        multiValued: false,
        description: 'Used to identify the relationship',
        required: false,
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'preferredLanguage',
        type: 'string',
        multiValued: false,
        description: "User's preferred written or spoken language",
        required: false,
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'locale',
        type: 'string',
        multiValued: false,
        description: 'Used to indicate the User locale',
        required: false,
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'timezone',
        type: 'string',
        multiValued: false,
        description: "The User's time zone",
        required: false,
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'active',
        type: 'boolean',
        multiValued: false,
        description: 'A Boolean value indicating active status',
        required: false,
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'password',
        type: 'string',
        multiValued: false,
        description: "The User's cleartext password",
        required: false,
        caseExact: false,
        mutability: 'writeOnly',
        returned: 'never',
        uniqueness: 'none',
      },
      {
        name: 'emails',
        type: 'complex',
        multiValued: true,
        description: 'Email addresses for the user',
        required: false,
        subAttributes: [
          {
            name: 'value',
            type: 'string',
            multiValued: false,
            description: 'Email address',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'display',
            type: 'string',
            multiValued: false,
            description: 'Display name',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'type',
            type: 'string',
            multiValued: false,
            description: 'Type (work, home, other)',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'primary',
            type: 'boolean',
            multiValued: false,
            description: 'Primary email',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
        ],
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'phoneNumbers',
        type: 'complex',
        multiValued: true,
        description: 'Phone numbers for the User',
        required: false,
        subAttributes: [
          {
            name: 'value',
            type: 'string',
            multiValued: false,
            description: 'Phone number',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'display',
            type: 'string',
            multiValued: false,
            description: 'Display name',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'type',
            type: 'string',
            multiValued: false,
            description: 'Type (work, home, mobile, etc)',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'primary',
            type: 'boolean',
            multiValued: false,
            description: 'Primary phone',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
        ],
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'addresses',
        type: 'complex',
        multiValued: true,
        description: 'Physical mailing addresses',
        required: false,
        subAttributes: [
          {
            name: 'formatted',
            type: 'string',
            multiValued: false,
            description: 'Full mailing address',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'streetAddress',
            type: 'string',
            multiValued: false,
            description: 'Street address',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'locality',
            type: 'string',
            multiValued: false,
            description: 'City or locality',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'region',
            type: 'string',
            multiValued: false,
            description: 'State or region',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'postalCode',
            type: 'string',
            multiValued: false,
            description: 'Zip or postal code',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'country',
            type: 'string',
            multiValued: false,
            description: 'Country',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'type',
            type: 'string',
            multiValued: false,
            description: 'Type (work, home, other)',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'primary',
            type: 'boolean',
            multiValued: false,
            description: 'Primary address',
            required: false,
            caseExact: false,
            mutability: 'readWrite',
            returned: 'default',
            uniqueness: 'none',
          },
        ],
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'groups',
        type: 'complex',
        multiValued: true,
        description: 'Group membership',
        required: false,
        subAttributes: [
          {
            name: 'value',
            type: 'string',
            multiValued: false,
            description: 'Group identifier',
            required: false,
            caseExact: false,
            mutability: 'readOnly',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: '$ref',
            type: 'reference',
            multiValued: false,
            description: 'URI of the group',
            required: false,
            caseExact: false,
            mutability: 'readOnly',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'display',
            type: 'string',
            multiValued: false,
            description: 'Display name',
            required: false,
            caseExact: false,
            mutability: 'readOnly',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'type',
            type: 'string',
            multiValued: false,
            description: 'Type of group',
            required: false,
            caseExact: false,
            mutability: 'readOnly',
            returned: 'default',
            uniqueness: 'none',
          },
        ],
        caseExact: false,
        mutability: 'readOnly',
        returned: 'default',
        uniqueness: 'none',
      },
    ],
  };
}

/**
 * SCIM Group Schema (RFC 7643 Section 4.2)
 */
export function getGroupSchema(): SCIMSchema {
  return {
    id: SCIM_SCHEMAS.CORE_GROUP,
    name: 'Group',
    description: 'Group',
    attributes: [
      {
        name: 'displayName',
        type: 'string',
        multiValued: false,
        description: 'Human-readable name for the Group',
        required: true,
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
      {
        name: 'members',
        type: 'complex',
        multiValued: true,
        description: 'List of members',
        required: false,
        subAttributes: [
          {
            name: 'value',
            type: 'string',
            multiValued: false,
            description: 'Member identifier',
            required: false,
            caseExact: false,
            mutability: 'immutable',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: '$ref',
            type: 'reference',
            multiValued: false,
            description: 'URI of member resource',
            required: false,
            caseExact: false,
            mutability: 'immutable',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'display',
            type: 'string',
            multiValued: false,
            description: 'Display name',
            required: false,
            caseExact: false,
            mutability: 'immutable',
            returned: 'default',
            uniqueness: 'none',
          },
          {
            name: 'type',
            type: 'string',
            multiValued: false,
            description: 'Type (User or Group)',
            required: false,
            caseExact: false,
            mutability: 'immutable',
            returned: 'default',
            uniqueness: 'none',
          },
        ],
        caseExact: false,
        mutability: 'readWrite',
        returned: 'default',
        uniqueness: 'none',
      },
    ],
  };
}
